### ISSUE TITLE
Plugin crash on SetCredentials 

### ISSUE THREAD

**Issue by KAMAELUA** [epicshaggy/capacitor-native-biometric#99]
Phone Xiaomi Redmi Note 9 MIUI 12.5.5
Android 11 RKQ1.200826.002

Plugin crashes on SetCredentials with error that cause app crash.

![image](https://github.com/epicshaggy/capacitor-native-biometric/assets/3611515/a97a0212-07de-4707-9297-74c0a4a26128)

<details>
  <summary>Exception stack</summary>

  ```
Serious error executing plugin
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:780)
	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.security.keystore.StrongBoxUnavailableException: Failed to generate key
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:328)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
	at com.epicshaggy.biometric.NativeBiometric.generateKey(NativeBiometric.java:300)
	at com.epicshaggy.biometric.NativeBiometric.getKey(NativeBiometric.java:311)
	at com.epicshaggy.biometric.NativeBiometric.encryptString(NativeBiometric.java:262)
	at com.epicshaggy.biometric.NativeBiometric.setCredentials(NativeBiometric.java:175)
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:780) 
	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
	at android.os.Handler.handleCallback(Handler.java:938) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at android.os.Looper.loop(Looper.java:236) 
	at android.os.HandlerThread.run(HandlerThread.java:67) 
Caused by: android.security.KeyStoreException: No StrongBox available
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:328) 
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612) 
	at com.epicshaggy.biometric.NativeBiometric.generateKey(NativeBiometric.java:300) 
	at com.epicshaggy.biometric.NativeBiometric.getKey(NativeBiometric.java:311) 
	at com.epicshaggy.biometric.NativeBiometric.encryptString(NativeBiometric.java:262) 
	at com.epicshaggy.biometric.NativeBiometric.setCredentials(NativeBiometric.java:175) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:780) 
	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
	at android.os.Handler.handleCallback(Handler.java:938) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at android.os.Looper.loop(Looper.java:236) 
	at android.os.HandlerThread.run(HandlerThread.java:67) 
  ```
</details>

Code sample that works on my other devices except Xiaomi. 

```typescript
if(verified) {
    try {
        await NativeBiometric.setCredentials({
            server,
            username,
            password,
        });
    } catch (e) {
        console.error('setCredentials', e);
    }
}
```

**Comment by KAMAELUA** [comment]
Duplicate of #97
